#!/usr/bin/env python3
"""Bake the settings-overlay bitmap font into src/font_atlas.h.

The overlay needs text on a GL window without pulling in SDL_ttf / stb_truetype / a
system font dependency.  We rasterize Pillow's bundled default font once, here, and
embed the result as a tight-packed alpha atlas plus per-glyph metrics.  Regenerate with:

    ~/venv/bin/python tools/bake_font.py > src/font_atlas.h

Pillow only; no runtime font dependency in the shipped binary.
"""

import sys

from PIL import Image, ImageDraw, ImageFont

SIZE = 15
FIRST, LAST = 32, 126
PAD = 1


def main() -> None:
    try:
        font = ImageFont.load_default(size=SIZE)
    except TypeError:  # Pillow < 10.1
        font = ImageFont.load_default()

    ascent, descent = font.getmetrics()
    line_height = ascent + descent + 2

    glyphs = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        x0, y0, x1, y1 = font.getbbox(ch)
        w, h = max(x1 - x0, 0), max(y1 - y0, 0)
        if w and h:
            im = Image.new("L", (w + 2 * PAD, h + 2 * PAD), 0)
            ImageDraw.Draw(im).text((PAD - x0, PAD - y0), ch, font=font, fill=255)
            data = list(im.tobytes())
            w += 2 * PAD
            h += 2 * PAD
            x0 -= PAD
            y0 -= PAD
        else:
            data = []
        glyphs.append((x0, y0, w, h, round(font.getlength(ch)), data))

    # Shelf-pack the tight glyph boxes into one texture.
    atlas_w = 256
    x = y = shelf_h = 0
    placed = []
    for (x0, y0, w, h, adv, data) in glyphs:
        if w == 0:
            placed.append((x0, y0, 0, 0, adv, 0, 0))
            continue
        if x + w > atlas_w:
            x = 0
            y += shelf_h
            shelf_h = 0
        placed.append((x0, y0, w, h, adv, x, y))
        x += w
        shelf_h = max(shelf_h, h)
    atlas_h = y + shelf_h

    atlas = bytearray(atlas_w * atlas_h)
    for (x0, y0, w, h, adv, ax, ay), (_, _, _, _, _, data) in zip(placed, glyphs):
        for row in range(h):
            dst = (ay + row) * atlas_w + ax
            atlas[dst:dst + w] = bytes(data[row * w:(row + 1) * w])

    out = sys.stdout
    out.write("// Generated by tools/bake_font.py -- do not edit.\n")
    out.write("// Pillow default font, %dpx: tight glyph bitmaps packed into one alpha atlas.\n" % SIZE)
    out.write("#pragma once\n\n")
    out.write("#define FONT_FIRST %d\n" % FIRST)
    out.write("#define FONT_LAST %d\n" % LAST)
    out.write("#define FONT_ASCENT %d\n" % ascent)
    out.write("#define FONT_DESCENT %d\n" % descent)
    out.write("#define FONT_LINE_HEIGHT %d\n" % line_height)
    out.write("#define FONT_ATLAS_W %d\n" % atlas_w)
    out.write("#define FONT_ATLAS_H %d\n\n" % atlas_h)
    out.write("typedef struct { short off_x, off_y; unsigned char w, h, adv; unsigned short u, v; } Glyph;\n\n")
    out.write("static const Glyph kGlyphs[%d] = {\n" % len(placed))
    for (x0, y0, w, h, adv, ax, ay) in placed:
        out.write("    {%4d,%4d,%3d,%3d,%3d,%4d,%4d},\n" % (x0, y0, w, h, adv, ax, ay))
    out.write("};\n\n")
    out.write("static const unsigned char kFontAtlas[%d] = {\n" % len(atlas))
    for i in range(0, len(atlas), 32):
        out.write("    " + "".join("%d," % b for b in atlas[i:i + 32]) + "\n")
    out.write("};\n")
    print("// %d glyphs, atlas %dx%d (%d bytes)" % (len(placed), atlas_w, atlas_h, len(atlas)), file=sys.stderr)


if __name__ == "__main__":
    main()
